//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Processors
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        public ApplicationUser()
        {
            this.UserCartRelations = new HashSet<UserCartRelation>();
        }
    
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Pincode { get; set; }
        public string CreditCard { get; set; }
        public string Password { get; set; }
        public int Id { get; set; }
        public string Role { get; set; }
        public Nullable<int> StoreId { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual ICollection<UserCartRelation> UserCartRelations { get; set; }
    }
}
