//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Processors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.UserCartRelations = new HashSet<UserCartRelation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> NameId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<int> StoreId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<UserCartRelation> UserCartRelations { get; set; }
    }
}
