//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Processors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.ApplicationUsers = new HashSet<ApplicationUser>();
            this.StoreProductAssociations = new HashSet<StoreProductAssociation>();
            this.UserCartRelations = new HashSet<UserCartRelation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }
        public virtual ICollection<StoreProductAssociation> StoreProductAssociations { get; set; }
        public virtual ICollection<UserCartRelation> UserCartRelations { get; set; }
    }
}
