//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Processors
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreProductAssociation
    {
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string HotDealCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> OffPercent { get; set; }
        public int Id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
