//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Processors
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCartRelation
    {
        public Nullable<int> CardId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> StoreId { get; set; }
        public int Id { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual Cart Cart { get; set; }
        public virtual Store Store { get; set; }
    }
}
